name: "🐞 Bug Report"
description: Report an issue or unexpected behavior in the Flightbook app
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out all fields clearly.
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Android
        - iOS
        - Web
        - Other / Unknown
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App version
      placeholder: e.g. 1.4.2
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: 1. … 2. … 3. …
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
  - type: textarea
    id: logs
    attributes:
      label: Additional info / screenshots
