name: "❓ Question / Other"
description: Ask a question or give general feedback
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: What do you want to ask or discuss?
      placeholder: Write your question here
      value: |
        Please describe your question or topic clearly.
